run:
	# using the hot reload command for the purposes of server development
	uvicorn main:app --port 58000 --reload

mock:
	# using the hot reload command for the purposes of server development
	IS_MOCK=true uvicorn main:app --port 58000 --reload
